### ISSUE TITLE
発言者・メッセージ・削除ボタン・編集ボタンを一行に表示する

### ISSUE THREAD

**Issue by aksh-t** [babyhotate/buri#32]
# 課題
投稿の編集、削除ボタンのレイアウトが変に見える
![image](https://user-images.githubusercontent.com/47623778/110234967-b2565880-7f70-11eb-8754-73ad61062f37.png)

**Comment by shellzu** [comment]
発言者・メッセージ・削除ボタン・編集ボタンを一行に表示する。
