### ISSUE TITLE
testing frameworkを選定/導入する

### ISSUE THREAD

**Issue by aksh-t** [babyhotate/buri#33]
Jest( https://jestjs.io/ja/ )かな

**Comment by aksh-t** [comment]
これを読めば良さそう
https://www.albertgao.xyz/2017/05/24/how-to-test-expressjs-with-jest-and-supertest/

**Comment by aksh-t** [comment]
# 各種ツールの比較
https://2020.stateofjs.com/ja-JP/technologies/testing/

# 所感
- Jestでよさそう
  - 最近よく選ばれていて、良さそう
  - ある程度の期間使われているので、情報が見つけやすそう

**Comment by aksh-t** [comment]
https://www.wakuwakubank.com/posts/525-javascript-jest/

**Comment by shellzu** [comment]
Jestに決定。
