### ISSUE TITLE
CommonJS/ESM問題

### ISSUE THREAD

**Issue by aksh-t** [babyhotate/buri#34]
# 問題意識
- リファクタリングでモジュール分割するにあたり、モジュールシステムをどうするべきか考える必要が出てきた

# やること
- どうするのがベストプラクティスか整理する

**Comment by aksh-t** [comment]
これを読むと良さそう
https://blog.hiroppy.me/entry/node-esm

**Comment by aksh-t** [comment]
これも
https://qiita.com/hagevvashi/items/8b4a7d3061bddd3b340e

**Comment by aksh-t** [comment]
この辺も
https://blog.jxck.io/entries/2017-08-15/universal-mjs-ecosystem.html

**Comment by aksh-t** [comment]
- 現状、エコシステムの対応が追いついてなさそうなので、CJSのままが無難そうではある
- が、実際のところやってみないとよくわからないので、ESMにしてみてもいいかもしれない

**Comment by shellzu** [comment]
話し合いの結果、CJSで一旦やっていく。
