### ISSUE TITLE
ユーザという概念を追加する

### ISSUE THREAD

**Issue by shellzu** [babyhotate/buri#38]
- 誰の投稿か分かるようにする

**Comment by inukawaii** [comment]
ユーザーの持つべき情報
- ユニークID（slackだとメンバーID）
- 表示名
-

**Comment by inukawaii** [comment]
# slackにおけるユーザー情報
- ユニークID（member ID）
- 表示名(display name)
- オフィシャルな名前（Full Name）
- 電話番号
- アイコン
- メールアドレス
- ステータス
- タイムゾーン
- 表示言語

# 今実装するユーザー情報
- ユニークID（member ID）
- 表示名(display name)
